spring:
  application:
    name: Electrify
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: electrify

#Use it when you want to see all the query logs
#logging.level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#logging.level.org.mongodb.driver: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Electrify
    description: Electrify
    version: 1.0.0

chargeMapKey: b68d6b86-ae22-452b-a116-d4007dc44481